bind-tcp 127.0.0.1:5348 -no-speed-check -no-cache
cache-size 0
speed-check-mode none
local-ttl 10
rr-ttl 10
rr-ttl-min 10
rr-ttl-max 10
rr-ttl-reply-max 10
address /bench.test/192.0.2.10
log-level error
audit-enable no
